name: streamsavor
description: "A minimal movie and anime streaming app"
publish_to: 'none'

version: 3.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  cached_network_image: ^3.3.1
  video_player: ^2.8.6
  flick_video_player: ^0.8.0
  visibility_detector: ^0.4.0+2
  html_main_element: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/error.png
    - assets/anime.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf